"""inventory schema definitions."""

inventory_schemas = {
    'create_inventory': {'additionalProperties': False,
 'properties': {'location': {'maxLength': 128, 'type': 'string'},
                'order_id': {'type': ['integer', 'null']},
                'product_model': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'product_name': {'maxLength': 128, 'type': 'string'},
                'quantity': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'safe_stock': {'minimum': 0, 'type': 'number'},
                'specification': {'maxLength': 256, 'type': 'string'},
                'unit': {'maxLength': 16, 'type': 'string'},
                'category': {'maxLength': 32, 'type': 'string'},
                'unit_cost': {'minimum': 0, 'type': 'number'}},
 'required': ['product_model'],
 'type': 'object'},
    'update_inventory': {'additionalProperties': False,
 'properties': {'location': {'maxLength': 128, 'type': 'string'},
                'product_model': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'product_name': {'maxLength': 128, 'type': 'string'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'safe_stock': {'minimum': 0, 'type': 'number'},
                'specification': {'maxLength': 256, 'type': 'string'},
                'unit': {'maxLength': 16, 'type': 'string'},
                'category': {'maxLength': 32, 'type': 'string'},
                'unit_cost': {'minimum': 0, 'type': 'number'}},
 'type': 'object'},
    'stock_movement': {'additionalProperties': False,
 'properties': {'inventory_id': {'minimum': 1, 'type': 'integer'},
                'order_id': {'type': ['integer', 'null']},
                'order_no': {'maxLength': 64, 'type': 'string'},
                'quantity': {'minimum': 0.001, 'type': 'number'},
                'lot_no': {'maxLength': 128, 'type': 'string'},
                'serial_no': {'maxLength': 128, 'type': 'string'},
                'idempotency_key': {'maxLength': 128, 'type': 'string'},
                'remark': {'maxLength': 512, 'type': 'string'}},
 'required': ['inventory_id', 'quantity'],
 'type': 'object'},
    'inventory_adjust': {'additionalProperties': False,
 'properties': {'actual_qty': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'}},
 'required': ['actual_qty'],
 'type': 'object'},
    'inventory_count_item': {'additionalProperties': False,
 'properties': {'actual_qty': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'task_id': {'minimum': 1, 'type': 'integer'}},
 'required': ['actual_qty'],
 'type': 'object'},
}
