"""inventory schema definitions."""

inventory_schemas = {
    'create_inventory': {'additionalProperties': False,
 'properties': {'location': {'maxLength': 128, 'type': 'string'},
                'order_id': {'type': ['integer', 'null']},
                'product_model': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'product_name': {'maxLength': 128, 'type': 'string'},
                'quantity': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'safe_stock': {'minimum': 0, 'type': 'number'},
                'specification': {'maxLength': 256, 'type': 'string'},
                'unit': {'maxLength': 16, 'type': 'string'},
                'category': {'maxLength': 32, 'type': 'string'},
                'unit_cost': {'minimum': 0, 'type': 'number'}},
 'required': ['product_model'],
 'type': 'object'},
    'update_inventory': {'additionalProperties': False,
 'properties': {'location': {'maxLength': 128, 'type': 'string'},
                'product_model': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'product_name': {'maxLength': 128, 'type': 'string'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'safe_stock': {'minimum': 0, 'type': 'number'},
                'specification': {'maxLength': 256, 'type': 'string'},
                'unit': {'maxLength': 16, 'type': 'string'},
                'category': {'maxLength': 32, 'type': 'string'},
                'unit_cost': {'minimum': 0, 'type': 'number'}},
 'type': 'object'},
    'stock_movement': {'additionalProperties': False,
 'properties': {'inventory_id': {'minimum': 1, 'type': 'integer'},
                'order_id': {'type': ['integer', 'null']},
                'order_no': {'maxLength': 64, 'type': 'string'},
                'quantity': {'minimum': 0.001, 'type': 'number'},
                'lot_no': {'maxLength': 128, 'type': 'string'},
                'serial_no': {'maxLength': 128, 'type': 'string'},
                'idempotency_key': {'maxLength': 128, 'type': 'string'},
                'remark': {'maxLength': 512, 'type': 'string'}},
 'required': ['inventory_id', 'quantity'],
 'type': 'object'},
    'inventory_adjust': {'additionalProperties': False,
 'properties': {'actual_qty': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'}},
 'required': ['actual_qty'],
 'type': 'object'},
    'inventory_count_item': {'additionalProperties': False,
 'properties': {'actual_qty': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'task_id': {'minimum': 1, 'type': 'integer'}},
 'required': ['actual_qty'],
 'type': 'object'},
    'inventory_allocation_preview': {'additionalProperties': False,
 'properties': {'compatibility_key': {'maxLength': 128, 'type': 'string'},
                'mode': {'enum': ['fifo', 'manual'], 'type': 'string'},
                'quantity': {'exclusiveMinimum': 0, 'type': 'number'},
                'reason': {'maxLength': 512, 'type': 'string'},
                'selected_inventory_ids': {'items': {'minimum': 1, 'type': 'integer'},
                                           'maxItems': 500, 'type': 'array'}},
 'required': ['quantity'],
 'type': 'object'},
    'inventory_allocation_outbound': {'additionalProperties': False,
 'properties': {'compatibility_key': {'maxLength': 128, 'type': 'string'},
                'idempotency_key': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'mode': {'enum': ['fifo', 'manual'], 'type': 'string'},
                'order_id': {'type': ['integer', 'null']},
                'order_no': {'maxLength': 64, 'type': 'string'},
                'preview_digest': {'maxLength': 128, 'type': 'string'},
                'quantity': {'exclusiveMinimum': 0, 'type': 'number'},
                'reason': {'maxLength': 512, 'type': 'string'},
                'selected_inventory_ids': {'items': {'minimum': 1, 'type': 'integer'},
                                           'maxItems': 500, 'type': 'array'}},
 'required': ['quantity', 'idempotency_key'],
 'type': 'object'},
    'inventory_allocation_reversal': {'additionalProperties': False,
 'properties': {'idempotency_key': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'reason': {'maxLength': 512, 'type': 'string'}},
 'required': ['idempotency_key'],
 'type': 'object'},
    'inventory_product_threshold': {'additionalProperties': False,
 'properties': {'safe_stock': {'minimum': 0, 'type': 'number'},
                'warning_buffer': {'minimum': 0, 'type': 'number'}},
 'required': ['safe_stock', 'warning_buffer'],
 'type': 'object'},
}
