"""materials schema definitions."""

materials_schemas = {
    'create_material': {'additionalProperties': True,
 'properties': {'location': {'maxLength': 128, 'type': 'string'},
                'material_type': {'maxLength': 64, 'type': 'string'},
                'name': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'quantity': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'safe_stock': {'minimum': 0, 'type': 'number'},
                'spec': {'maxLength': 128, 'type': 'string'},
                'supplier_id': {'type': ['integer', 'null', 'string']},
                'unit': {'maxLength': 32, 'type': 'string'},
                'unit_price': {'minimum': 0, 'type': 'number'}},
 'required': ['name'],
 'type': 'object'},
    'update_material': {'additionalProperties': True,
 'properties': {'location': {'maxLength': 128, 'type': 'string'},
                'material_type': {'maxLength': 64, 'type': 'string'},
                'name': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'quantity': {'minimum': 0, 'type': 'number'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'safe_stock': {'minimum': 0, 'type': 'number'},
                'spec': {'maxLength': 128, 'type': 'string'},
                'supplier_id': {'type': ['integer', 'null', 'string']},
                'unit': {'maxLength': 32, 'type': 'string'},
                'unit_price': {'minimum': 0, 'type': 'number'}},
 'type': 'object'},
}
