"""orders schema definitions."""

orders_schemas = {
    'batch_orders': {'additionalProperties': False,
 'properties': {'orders': {'items': {'additionalProperties': True,
                                     'properties': {'customer': {'maxLength': 128, 'type': 'string'},
                                                    'deadline': {'maxLength': 32, 'type': 'string'},
                                                    'order_no': {'maxLength': 64, 'minLength': 1, 'type': 'string'},
                                                    'plan_end': {'maxLength': 32, 'type': 'string'},
                                                    'plan_start': {'maxLength': 32, 'type': 'string'},
                                                    'product_name': {'maxLength': 128, 'type': 'string'},
                                                    'quantity': {'maximum': 99999, 'minimum': 1, 'type': 'integer'},
                                                    'remark': {'maxLength': 1024, 'type': 'string'}},
                                     'required': ['order_no'],
                                     'type': 'object'},
                           'maxItems': 200,
                           'type': 'array'}},
 'required': ['orders'],
 'type': 'object'},
    'create_order': {'additionalProperties': True,
 'properties': {'customer': {'maxLength': 128, 'type': 'string'},
                'customer_id': {'type': ['integer', 'null']},
                'deadline': {'maxLength': 32, 'type': 'string'},
                'order_no': {'maxLength': 64, 'minLength': 1, 'type': 'string'},
                'plan_end': {'maxLength': 32, 'type': 'string'},
                'plan_start': {'maxLength': 32, 'type': 'string'},
                'process_ids': {'items': {'type': 'integer'}, 'maxItems': 50, 'type': 'array'},
                'product_code': {'maxLength': 64, 'type': 'string'},
                'product_name': {'maxLength': 128, 'type': 'string'},
                'production_line_id': {'type': ['integer', 'null']},
                'quantity': {'maximum': 99999, 'minimum': 1, 'type': 'integer'},
                'remark': {'maxLength': 1024, 'type': 'string'},
                'route_id': {'type': ['integer', 'null']}},
 'type': 'object'},
    'update_order': {'additionalProperties': True,
 'properties': {'customer': {'maxLength': 128, 'type': 'string'},
                'customer_id': {'type': ['integer', 'null']},
                'deadline': {'maxLength': 32, 'type': 'string'},
                'plan_end': {'maxLength': 32, 'type': 'string'},
                'plan_start': {'maxLength': 32, 'type': 'string'},
                'product_code': {'maxLength': 64, 'type': 'string'},
                'product_name': {'maxLength': 128, 'type': 'string'},
                'production_line_id': {'type': ['integer', 'null']},
                'quantity': {'maximum': 99999, 'minimum': 1, 'type': 'integer'},
                'remark': {'maxLength': 1024, 'type': 'string'},
                'route_id': {'type': ['integer', 'null']},
                'status': {'enum': ['pending', 'producing', 'completed', 'cancelled', 'paused'], 'type': 'string'}},
 'type': 'object'},
}
