"""processes schema definitions."""

processes_schemas = {
    'process_price': {'additionalProperties': False,
 'properties': {'effective_date': {'maxLength': 32, 'type': 'string'},
                'process_id': {'minimum': 1, 'type': 'integer'},
                'product_id': {'type': ['integer', 'null']},
                'remark': {'maxLength': 512, 'type': 'string'},
                'status': {'enum': ['active', 'inactive'], 'type': 'string'},
                'unit_price': {'minimum': 0, 'type': 'number'}},
 'required': ['process_id', 'unit_price'],
 'type': 'object'},
    'route_price': {'additionalProperties': False,
 'properties': {'effective_date': {'maxLength': 32, 'type': 'string'},
                'process_id': {'minimum': 1, 'type': 'integer'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'route_id': {'minimum': 1, 'type': 'integer'},
                'status': {'enum': ['active', 'inactive'], 'type': 'string'},
                'unit_price': {'minimum': 0, 'type': 'number'}},
 'required': ['route_id', 'process_id', 'unit_price'],
 'type': 'object'},
    'process_route': {'additionalProperties': False,
 'properties': {'category': {'maxLength': 64, 'type': 'string'},
                'description': {'maxLength': 512, 'type': 'string'},
                'name': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'processes': {'items': {'additionalProperties': False,
                                        'properties': {'process_id': {'minimum': 1, 'type': 'integer'},
                                                       'required_audit': {'maximum': 1,
                                                                          'minimum': 0,
                                                                          'type': 'integer'}},
                                        'required': ['process_id'],
                                        'type': 'object'},
                              'maxItems': 50,
                              'type': 'array'}},
 'required': ['name', 'processes'],
 'type': 'object'},
    'create_process': {'additionalProperties': False,
 'properties': {'category': {'maxLength': 64, 'type': 'string'},
                'description': {'maxLength': 512, 'type': 'string'},
                'name': {'maxLength': 64, 'minLength': 1, 'pattern': '^[一-龥a-zA-Z0-9\\s\\-/().+#]+$', 'type': 'string'},
                'seq_order': {'minimum': 0, 'type': 'integer'},
                'status': {'enum': ['active', 'inactive'], 'type': 'string'}},
 'required': ['name'],
 'type': 'object'},
    'update_process': {'additionalProperties': False,
 'properties': {'category': {'maxLength': 64, 'type': 'string'},
                'description': {'maxLength': 512, 'type': 'string'},
                'name': {'maxLength': 64, 'minLength': 1, 'pattern': '^[一-龥a-zA-Z0-9\\s\\-/().+#]+$', 'type': 'string'},
                'seq_order': {'minimum': 0, 'type': 'integer'},
                'status': {'enum': ['active', 'inactive'], 'type': 'string'}},
 'type': 'object'},
}
