"""products schema definitions."""

products_schemas = {
    'create_product': {'additionalProperties': False,
 'properties': {'category': {'maxLength': 32, 'type': 'string'},
                'description': {'maxLength': 1024, 'type': 'string'},
                'lower_opening': {'maxLength': 64, 'type': 'string'},
                'model': {'maxLength': 64, 'type': 'string'},
                'plate_thickness': {'maxLength': 32, 'type': 'string'},
                'price': {'minimum': 0, 'type': 'number'},
                'product_code': {'maxLength': 128, 'type': 'string'},
                'product_name': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'route_id': {'type': ['integer', 'null']},
                'spec': {'maxLength': 256, 'type': 'string'},
                'style': {'maxLength': 64, 'type': 'string'},
                'upper_opening': {'maxLength': 64, 'type': 'string'},
                'weight': {'minimum': 0, 'type': 'number'}},
 'required': ['product_name'],
 'type': 'object'},
    'update_product': {'additionalProperties': False,
 'properties': {'category': {'maxLength': 32, 'type': 'string'},
                'description': {'maxLength': 1024, 'type': 'string'},
                'lower_opening': {'maxLength': 64, 'type': 'string'},
                'model': {'maxLength': 64, 'type': 'string'},
                'plate_thickness': {'maxLength': 32, 'type': 'string'},
                'price': {'minimum': 0, 'type': 'number'},
                'product_code': {'maxLength': 128, 'type': 'string'},
                'product_name': {'maxLength': 128, 'minLength': 1, 'type': 'string'},
                'route_id': {'type': ['integer', 'null']},
                'spec': {'maxLength': 256, 'type': 'string'},
                'style': {'maxLength': 64, 'type': 'string'},
                'upper_opening': {'maxLength': 64, 'type': 'string'},
                'weight': {'minimum': 0, 'type': 'number'}},
 'type': 'object'},
}
