"""scan schema definitions."""

scan_schemas = {
    'work_report': {'additionalProperties': False,
 'properties': {'order_id': {'minimum': 1, 'type': 'integer'},
                'process_id': {'minimum': 1, 'type': 'integer'},
                'quantity': {'maximum': 99999, 'minimum': 1, 'type': 'integer'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'serial_no': {'maxLength': 64, 'type': 'string'},
                'type': {'enum': ['normal', 'rework', 'scrap'], 'type': 'string'}},
 'required': ['order_id', 'process_id'],
 'type': 'object'},
    'mobile_scan': {'additionalProperties': False,
 'properties': {'code': {'maxLength': 256, 'minLength': 1, 'type': 'string'},
                'latitude': {'maxLength': 32, 'type': 'string'},
                'longitude': {'maxLength': 32, 'type': 'string'}},
 'required': ['code'],
 'type': 'object'},
    'mobile_report': {'additionalProperties': False,
 'properties': {'latitude': {'maxLength': 32, 'type': 'string'},
                'longitude': {'maxLength': 32, 'type': 'string'},
                'order_id': {'minimum': 1, 'type': 'integer'},
                'process_id': {'minimum': 1, 'type': 'integer'},
                'quantity': {'maximum': 99999, 'minimum': 1, 'type': 'integer'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'serial_no': {'maxLength': 64, 'type': 'string'},
                'type': {'enum': ['normal', 'rework', 'scrap'], 'type': 'string'}},
 'required': ['order_id', 'process_id'],
 'type': 'object'},
    'scan_order': {'additionalProperties': False,
 'properties': {'order_id': {'minimum': 1, 'type': 'integer'},
                'process_id': {'minimum': 1, 'type': 'integer'},
                'quantity': {'maximum': 99999, 'minimum': 1, 'type': 'integer'},
                'remark': {'maxLength': 512, 'type': 'string'},
                'serial_no': {'maxLength': 64, 'type': 'string'},
                'type': {'enum': ['normal', 'rework', 'scrap', 'stock_in'], 'type': 'string'}},
 'required': ['order_id'],
 'type': 'object'},
}
