"""users schema definitions."""

users_schemas = {
    'create_user': {'additionalProperties': False,
 'properties': {'email': {'format': 'email', 'maxLength': 128, 'type': 'string'},
                'employee_no': {'maxLength': 32, 'type': 'string'},
                'group_name': {'maxLength': 64, 'type': 'string'},
                'name': {'maxLength': 64, 'minLength': 1, 'pattern': '^[一-龥a-zA-Z0-9\\s\\-/().+#]+$', 'type': 'string'},
                'nickname': {'maxLength': 64, 'type': 'string'},
                'password': {'maxLength': 128, 'minLength': 6, 'type': 'string'},
                'phone': {'maxLength': 32, 'type': 'string'},
                'position_id': {'type': ['integer', 'null']},
                'process_ids': {'maxLength': 256, 'type': 'string'},
                'role': {'enum': ['admin', 'worker'], 'type': 'string'},
                'role_id': {'type': ['integer', 'null']},
                'status': {'enum': ['active', 'inactive'], 'type': 'string'},
                'username': {'maxLength': 64, 'minLength': 2, 'type': 'string'}},
 'required': ['username', 'name'],
 'type': 'object'},
    'update_user': {'additionalProperties': False,
 'properties': {'email': {'format': 'email', 'maxLength': 128, 'type': 'string'},
                'employee_no': {'maxLength': 32, 'type': 'string'},
                'group_name': {'maxLength': 64, 'type': 'string'},
                'name': {'maxLength': 64, 'minLength': 1, 'type': 'string'},
                'nickname': {'maxLength': 64, 'type': 'string'},
                'password': {'maxLength': 128, 'minLength': 6, 'type': 'string'},
                'phone': {'maxLength': 32, 'type': 'string'},
                'position_id': {'type': ['integer', 'null']},
                'process_ids': {'maxLength': 256, 'type': 'string'},
                'role': {'enum': ['admin', 'worker'], 'type': 'string'},
                'status': {'enum': ['active', 'inactive'], 'type': 'string'},
                'username': {'maxLength': 64, 'minLength': 2, 'type': 'string'}},
 'type': 'object'},
}
