import { request, buildQuery } from './client.js'

export const performanceApi = {
  performanceOverview: (params) => request('GET', '/api/performance/overview' + buildQuery(params)),
  performanceScores: (params) => request('GET', '/api/performance/scores' + buildQuery(params)),
  performanceRules: () => request('GET', '/api/performance/rules'),
  performancePlans: (params) => request('GET', '/api/performance/plans' + buildQuery(params)),
  createPerformancePlan: (data) => request('POST', '/api/performance/plans', data),
  getPerformancePlan: (id) => request('GET', '/api/performance/plans/' + id),
  transitionPerformancePlan: (id, data) => request('POST', '/api/performance/plans/' + id + '/transitions', data),
  addPerformancePlanEvidence: (id, data) => request('POST', '/api/performance/plans/' + id + '/evidence', data),
  reassessPerformancePlan: (id, data) => request('POST', '/api/performance/plans/' + id + '/reassessments', data),

  listPerformanceBatches: (params) => request('GET', '/api/performance/batches' + buildQuery(params)),
  createPerformanceBatch: (data) => request('POST', '/api/performance/batches', data),
  performanceBatchDetail: (id, params) => request('GET', '/api/performance/batches/' + id + buildQuery(params)),
  submitPerformanceSupervisorReview: (id, data) => request('POST', '/api/performance/batches/' + id + '/submit-supervisor-review', data),
  savePerformanceSupervisorReview: (id, userId, data) => request('POST', '/api/performance/batches/' + id + '/members/' + userId + '/reviews', data),
  submitPerformanceApproval: (id, data) => request('POST', '/api/performance/batches/' + id + '/submit-approval', data),
  approvePerformanceBatch: (id, data) => request('POST', '/api/performance/batches/' + id + '/approve', data),
  returnPerformanceBatch: (id, data) => request('POST', '/api/performance/batches/' + id + '/return', data),
  cancelPerformanceBatch: (id, data) => request('POST', '/api/performance/batches/' + id + '/cancel', data),
  createPerformanceRevision: (id, data) => request('POST', '/api/performance/batches/' + id + '/revisions', data),
  performanceBatchExceptions: (id, params) => request('GET', '/api/performance/batches/' + id + '/exceptions' + buildQuery(params)),
  performanceBatchComparison: (id, compareBatchId) => request('GET', '/api/performance/batches/' + id + '/comparison' + buildQuery({ compare_batch_id: compareBatchId })),
  performanceBatchIntegrity: (id, params) => request('GET', '/api/performance/batches/' + id + '/integrity' + buildQuery(params)),

  listPerformanceRuleVersions: (params) => request('GET', '/api/performance/rule-versions' + buildQuery(params)),
  createPerformanceRuleVersion: (data) => request('POST', '/api/performance/rule-versions', data),
  updatePerformanceRuleVersion: (id, data) => request('PUT', '/api/performance/rule-versions/' + id, data),
  publishPerformanceRuleVersion: (id, data) => request('POST', '/api/performance/rule-versions/' + id + '/publish', data),
  listPerformanceTargets: (params) => request('GET', '/api/performance/position-target-versions' + buildQuery(params)),
  createPerformanceTarget: (data) => request('POST', '/api/performance/position-target-versions', data),
  updatePerformanceTarget: (id, data) => request('PUT', '/api/performance/position-target-versions/' + id, data),
  approvePerformanceTarget: (id, data) => request('POST', '/api/performance/position-target-versions/' + id + '/approve', data),
  resolvePerformanceTarget: (params) => request('GET', '/api/performance/position-target-versions/resolve' + buildQuery(params)),

  getPerformanceDepartmentScopes: (userId) => request('GET', '/api/performance/department-scopes/' + userId),
  replacePerformanceDepartmentScopes: (userId, departmentIds) => request('PUT', '/api/performance/department-scopes/' + userId, { department_ids: departmentIds }),
  listPerformanceDepartments: () => request('GET', '/api/departments'),
}
