import { request, buildQuery } from './client.js'

export const wagesApi = {
  listPayrollBatches: (params) => request('GET', '/api/payroll/batches' + buildQuery(params)),
  createPayrollBatch: (data) => request('POST', '/api/payroll/batches', data),
  getPayrollBatch: (id) => request('GET', '/api/payroll/batches/' + id),
  regeneratePayrollBatch: (id, rowVersion) => request('POST', `/api/payroll/batches/${id}/regenerate`, { row_version: rowVersion }),
  submitPayrollBatch: (id, rowVersion) => request('POST', `/api/payroll/batches/${id}/submit`, { row_version: rowVersion }),
  lockPayrollBatch: (id, rowVersion) => request('POST', `/api/payroll/batches/${id}/lock`, { row_version: rowVersion }),
  confirmPayrollBatch: (id, rowVersion) => request('POST', `/api/payroll/batches/${id}/confirm`, { row_version: rowVersion }),
  voidPayrollBatch: (id, rowVersion, reason) => request('POST', `/api/payroll/batches/${id}/void`, { row_version: rowVersion, reason }),
  revisePayrollBatch: (id, data) => request('POST', `/api/payroll/batches/${id}/revisions`, data),
  comparePayrollBatches: (id, otherId) => request('GET', `/api/payroll/batches/${id}/compare/${otherId}`),
  getMyPayroll: (payrollMonth) => request('GET', '/api/payroll/me' + buildQuery({ payroll_month: payrollMonth })),
  listPayrollExceptions: (params) => request('GET', '/api/payroll/exceptions' + buildQuery(params)),
  proposePayrollException: (id, data) => request('POST', `/api/payroll/exceptions/${id}/propose`, data),
  approvePayrollException: (id) => request('POST', `/api/payroll/exceptions/${id}/approve`, {}),
  listPayrollAdjustments: (params) => request('GET', '/api/payroll/adjustments' + buildQuery(params)),
  createPayrollAdjustment: (data) => request('POST', '/api/payroll/adjustments', data),
  reversePayrollAdjustment: (id, reason) => request('POST', `/api/payroll/adjustments/${id}/reverse`, { reason }),
  listRoutePriceVersions: (params) => request('GET', '/api/route-price-versions' + buildQuery(params)),
  getRoutePriceVersionReference: (params) => request('GET', '/api/route-price-versions/reference' + buildQuery(params)),
  createRoutePriceVersion: (data) => request('POST', '/api/route-price-versions', data),
  voidRoutePriceVersion: (id, data) => request('POST', `/api/route-price-versions/${id}/void`, data),
  approveRoutePriceVersion: (id, rowVersion) => request('POST', `/api/route-price-versions/${id}/approve`, { row_version: rowVersion }),
  listWages:          (params) => request('GET', '/api/wages' + buildQuery(params)),
  getSnapshotStatus:  (yearMonth) => request('GET', '/api/wages/snapshot-status' + buildQuery({ year_month: yearMonth })),
  getMonthlySummary:  (params) => request('GET', '/api/wages/monthly-summary' + buildQuery(params)),
  getProcessSummary:  (yearMonth) => request('GET', '/api/wages/process-summary' + buildQuery({ year_month: yearMonth })),
  listAdjustments:    (yearMonth) => request('GET', '/api/wages/adjustments' + buildQuery({ year_month: yearMonth })),
  getWageTrends:      (months) => request('GET', '/api/wages/trends' + buildQuery({ months })),
  getPositionSummary: (yearMonth) => request('GET', '/api/wages/position-summary' + buildQuery({ year_month: yearMonth })),
  getWagePrediction:  (months) => request('GET', '/api/wages/prediction' + buildQuery({ months })),
}
