#!/usr/bin/env python3
"""Export backend permission catalog constants for frontend fallback use."""
import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from modules.permission_catalog import ACTION_PAGE_MAP, PAGE_RULES, SIDEBAR_ITEMS

OUTPUT = PROJECT_ROOT / "frontend" / "src" / "lib" / "permissionFallback.generated.js"


def js_const(name, value):
    payload = json.dumps(value, ensure_ascii=False, indent=2)
    return f"export const {name} = {payload}\n"


def render_catalog():
    content = "// Generated by scripts/export_permission_catalog.py. Do not edit by hand.\n"
    content += js_const("SIDEBAR_ITEMS", SIDEBAR_ITEMS)
    content += js_const("PAGE_RULE_TREE", PAGE_RULES)
    content += js_const("ACTION_PAGE_MAP", ACTION_PAGE_MAP)
    return content


def main(argv=None):
    parser = argparse.ArgumentParser(description="Export frontend permission fallback catalog.")
    parser.add_argument("--check", action="store_true", help="fail if the generated file is out of date")
    parser.add_argument("--stdout", action="store_true", help="print generated content instead of writing the file")
    args = parser.parse_args(argv)

    content = render_catalog()
    if args.stdout:
        sys.stdout.write(content)
        return 0
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(PROJECT_ROOT)} is out of date", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
