<template>
  <div class="qm-page">
    <div class="summary-bar">
      <div class="summary-item"><span class="s-icon">待</span><div><div class="s-val">{{ dashboard.tasks?.pending || 0 }}</div><div class="s-label">待检任务</div></div></div>
      <div class="summary-item"><span class="s-icon">逾</span><div><div class="s-val text-danger">{{ dashboard.tasks?.overdue || 0 }}</div><div class="s-label">逾期任务</div></div></div>
      <div class="summary-item"><span class="s-icon">异</span><div><div class="s-val text-warning">{{ dashboard.ncr?.open || 0 }}</div><div class="s-label">未关闭不合格</div></div></div>
      <div class="summary-item"><span class="s-icon">复</span><div><div class="s-val">{{ dashboard.ncr?.pending_reinspection || 0 }}</div><div class="s-label">待复检</div></div></div>
      <div class="summary-item"><span class="s-icon">率</span><div><div class="s-val text-success">{{ dashboard.pass_rate || 0 }}%</div><div class="s-label">检验合格率</div></div></div>
      <div class="summary-item"><span class="s-icon">校</span><div><div class="s-val text-danger">{{ dashboard.gauges?.overdue || 0 }}</div><div class="s-label">量具校准逾期</div></div></div>
      <div class="summary-item"><span class="s-icon">审</span><div><div class="s-val text-warning">{{ dashboard.review_pending?.total || 0 }}</div><div class="s-label">待审核记录</div></div></div>
      <div class="summary-item"><span class="s-icon">隔</span><div><div class="s-val text-danger">{{ dashboard.quality_holds?.total || 0 }}</div><div class="s-label">质量隔离库存</div></div></div>
      <div class="summary-item"><span class="s-icon">限</span><div><div class="s-val text-danger">{{ dashboard.ncr?.overdue || 0 }}</div><div class="s-label">逾期质量异常</div></div></div>
    </div>

    <div v-if="activeTab==='records' && canReview && records.some(row => row.review_status === 'unreviewed')" class="card qm-review-queue">
      <div class="qm-section-head"><h4>待审核检验记录</h4><span class="cell-muted">审核驳回会自动生成质量异常并锁定关联库存</span></div>
      <div v-for="row in records.filter(item => item.review_status === 'unreviewed')" :key="'review-' + row.id" class="qm-review-item">
        <div><code>{{ row.task_no || ('检验记录 #' + row.id) }}</code><span class="cell-muted">{{ row.order_no || '-' }} / {{ row.process_name || '-' }} / {{ row.result }}</span></div>
        <button class="btn btn-primary btn-sm" @click="openReview(row)">审核</button>
      </div>
    </div>

    <div class="card qm-shell">
      <div class="card-header qm-header">
        <h3>质量管理</h3>
        <div class="qm-tabs">
          <button v-for="tab in visibleTabs" :key="tab.key" class="tab-btn" :class="{active:activeTab===tab.key}" @click="switchTab(tab.key)">{{ tab.label }}</button>
        </div>
        <div class="qm-actions">
          <input v-if="!['overview','analytics','rules'].includes(activeTab)" v-model="keyword" class="form-input qm-search" placeholder="搜索" @keyup.enter="loadActive">
          <select v-if="['tasks','records','ncr','capa','suppliers','gauges'].includes(activeTab)" v-model="filterStatus" class="form-input qm-filter" @change="loadActive">
            <option value="">全部状态</option>
            <template v-if="activeTab==='tasks'"><option value="pending">待检</option><option value="in_progress">检验中</option><option value="passed">已通过</option><option value="failed">不合格</option></template>
            <template v-if="activeTab==='records' || activeTab==='suppliers'"><option value="pass">合格</option><option value="rework">返修</option><option value="scrap">报废</option></template>
            <template v-if="activeTab==='ncr'"><option value="open">待处置</option><option value="processing">处理中</option><option value="pending_reinspection">待复检</option><option value="closed">已关闭</option></template>
            <template v-if="activeTab==='capa'"><option value="open">待分析</option><option value="processing">执行中</option><option value="verified">已验证</option><option value="closed">已关闭</option></template>
            <template v-if="activeTab==='gauges'"><option value="active">在用</option><option value="suspended">停用</option><option value="scrapped">报废</option></template>
          </select>
          <button v-if="!['overview','analytics','rules'].includes(activeTab)" class="btn btn-default btn-sm" @click="loadActive">查询</button>
          <button v-if="primaryLabel" class="btn btn-primary btn-sm" @click="openPrimary">{{ primaryLabel }}</button>
        </div>
      </div>

      <div class="card-body qm-body">
        <section v-if="activeTab==='overview'" class="qm-overview">
          <div class="qm-section-head"><h4>待审核检验</h4><button class="btn btn-default btn-sm" @click="switchTab('records')">查看全部</button></div>
          <div class="table-wrap">
            <table v-if="dashboard.pending_reviews?.length" class="data-table"><thead><tr><th>检验记录</th><th>订单</th><th>工序</th><th>结果</th><th>检验员</th><th>时间</th></tr></thead>
              <tbody><tr v-for="row in dashboard.pending_reviews" :key="row.id"><td><code>{{ row.task_no || ('记录 #' + row.id) }}</code></td><td>{{ row.order_no || '-' }}</td><td>{{ row.process_name || '-' }}</td><td><span class="badge" :class="resultClass(row.result)">{{ resultLabel(row.result) }}</span></td><td>{{ row.inspector_name || '-' }}</td><td>{{ row.inspected_at || '-' }}</td></tr></tbody>
            </table><div v-else class="empty"><div class="empty-text">暂无待审核检验记录</div></div>
          </div>
          <div class="qm-section-head"><h4>待处理检验</h4><button class="btn btn-default btn-sm" @click="switchTab('tasks')">查看全部</button></div>
          <div class="table-wrap">
            <table v-if="dashboard.recent_tasks?.length" class="data-table"><thead><tr><th>任务号</th><th>类型</th><th>订单</th><th>工序</th><th>状态</th><th>要求完成</th></tr></thead>
              <tbody><tr v-for="row in dashboard.recent_tasks" :key="row.task_no"><td><code>{{ row.task_no }}</code></td><td>{{ typeLabel(row.inspection_type) }}</td><td>{{ row.order_no || '-' }}</td><td>{{ row.process_name || '-' }}</td><td><span class="badge" :class="statusClass(row.status)">{{ taskStatusLabel(row.status) }}</span></td><td>{{ row.due_at || '-' }}</td></tr></tbody>
            </table><div v-else class="empty"><div class="empty-text">暂无待处理检验</div></div>
          </div>
          <div class="qm-section-head qm-second"><h4>未关闭不合格</h4><button class="btn btn-default btn-sm" @click="switchTab('ncr')">查看全部</button></div>
          <div class="table-wrap">
            <table v-if="dashboard.open_ncr?.length" class="data-table"><thead><tr><th>不合格单</th><th>订单</th><th>工序</th><th>缺陷等级</th><th>状态</th><th>要求完成</th></tr></thead>
              <tbody><tr v-for="row in dashboard.open_ncr" :key="row.ncr_no"><td><code>{{ row.ncr_no }}</code></td><td>{{ row.order_no || '-' }}</td><td>{{ row.process_name || '-' }}</td><td>{{ defectLevelLabel(row.defect_level) }}</td><td><span class="badge" :class="statusClass(row.status)">{{ ncrStatusLabel(row.status) }}</span></td><td>{{ row.due_at || '-' }}</td></tr></tbody>
            </table><div v-else class="empty"><div class="empty-text">暂无未关闭不合格</div></div>
          </div>
        </section>

        <section v-else-if="activeTab==='tasks'">
          <div class="table-wrap"><table v-if="tasks.length" class="data-table qm-wide"><thead><tr><th>任务号</th><th>类型/触发</th><th>订单/产品</th><th>工序/工件</th><th>标准</th><th>抽样</th><th>门禁</th><th>负责人</th><th>状态</th><th>要求完成</th><th>操作</th></tr></thead>
            <tbody><tr v-for="row in tasks" :key="row.id" :class="{ 'qm-overdue-row': row.overdue }">
              <td><code>{{ row.task_no }}</code></td><td>{{ typeLabel(row.inspection_type) }}<div class="cell-muted">{{ triggerLabel(row.trigger_type) }}</div></td><td>{{ row.order_no || row.shipment_no || row.supplier_name || '-' }}<div class="cell-muted">{{ row.product_name || row.material_name || '-' }}</div></td><td>{{ row.process_name || '-' }}<div class="cell-muted">{{ row.serial_no || row.batch_no || '批次' }}</div></td><td>{{ row.standard_no || '-' }}</td><td>{{ row.sample_qty }}</td><td><span class="badge" :class="row.gate_mode==='hard'?'badge-danger':row.gate_mode==='soft'?'badge-warning':'badge-info'">{{ gateLabel(row.gate_mode) }}</span></td><td>{{ row.assigned_name || '未分配' }}</td><td><span class="badge" :class="statusClass(row.status)">{{ taskStatusLabel(row.status) }}</span></td><td>{{ row.due_at || '-' }}<div v-if="row.overdue" class="text-danger cell-muted">已逾期</div></td>
              <td class="qm-row-actions"><button v-if="row.status==='pending' && canInspect" class="btn btn-default btn-sm" @click="startTask(row)">开始</button><button v-if="['pending','in_progress'].includes(row.status) && canInspect" class="btn btn-primary btn-sm" @click="openInspection(row)">检验</button></td>
            </tr></tbody></table><div v-else class="empty"><div class="empty-text">暂无检验任务</div></div></div>
        </section>

        <section v-else-if="activeTab==='records'">
          <div class="table-wrap"><table v-if="records.length" class="data-table qm-wide"><thead><tr><th>检验时间</th><th>任务号</th><th>订单/产品</th><th>工序/工件</th><th>类型</th><th>检验数量</th><th>判定</th><th>评分</th><th>缺陷</th><th>质检员</th><th>不合格单</th></tr></thead>
            <tbody><tr v-for="row in records" :key="row.id"><td>{{ row.inspected_at || row.created_at }}</td><td><code>{{ row.task_no || '-' }}</code></td><td>{{ row.order_no || '-' }}<div class="cell-muted">{{ row.product_name || '-' }}</div></td><td>{{ row.process_name || '-' }}<div class="cell-muted">{{ row.serial_no || '批次' }}</div></td><td>{{ typeLabel(row.inspection_type) }}</td><td>{{ row.quantity_checked }} / 合格 {{ row.quantity_passed }} / 不合格 {{ row.quantity_failed }}</td><td><span class="badge" :class="resultClass(row.result)">{{ resultLabel(row.result) }}</span></td><td>{{ row.score_total || '-' }}</td><td>{{ defectLevelLabel(row.defect_level) }}<div class="cell-muted">{{ row.defect_category || '-' }}</div></td><td>{{ row.inspector_name || '-' }}</td><td><code>{{ row.ncr_no || '-' }}</code></td></tr></tbody>
          </table><div v-else class="empty"><div class="empty-text">暂无检验记录</div></div></div>
        </section>

        <div v-if="activeTab==='ncr' && ncrItems.length" class="qm-ncr-detail-list">
          <div v-for="row in ncrItems" :key="'detail-' + row.id" class="qm-ncr-detail-link">
            <code>{{ row.ncr_no }}</code><span>{{ row.description || '质量异常' }}</span><button class="btn btn-default btn-sm" @click="openNcrDetail(row)">查看详情</button>
          </div>
        </div>

        <section v-if="activeTab==='standards'">
          <div class="qm-segments"><button class="tab-btn" :class="{active:standardMode==='standards'}" @click="standardMode='standards';loadStandards()">质量标准</button><button class="tab-btn" :class="{active:standardMode==='plans'}" @click="standardMode='plans';loadPlans()">检验方案</button></div>
          <div v-if="standardMode==='standards'" class="table-wrap"><table v-if="standards.length" class="data-table qm-wide"><thead><tr><th>标准编码</th><th>名称</th><th>适用范围</th><th>检验类型</th><th>版本</th><th>项目数</th><th>抽样</th><th>最低分</th><th>门禁</th><th>状态</th><th>操作</th></tr></thead>
            <tbody><tr v-for="row in standards" :key="row.id"><td><code>{{ row.standard_no }}</code></td><td>{{ row.name }}</td><td>{{ scopeLabel(row) }}</td><td>{{ typeLabel(row.inspection_type) }}</td><td>V{{ row.version }}</td><td>{{ row.item_count }}</td><td>{{ samplingLabel(row) }}</td><td>{{ row.min_score }}</td><td>{{ gateLabel(row.gate_mode) }}</td><td><span class="badge" :class="row.status==='active'?'badge-success':'badge-info'">{{ row.status==='active'?'启用':'停用' }}</span></td><td class="qm-row-actions"><button v-if="canStandards" class="btn btn-default btn-sm" @click="editStandard(row)">编辑</button><button v-if="canStandards && row.status==='active'" class="btn btn-danger btn-sm" @click="archiveStandard(row)">停用</button></td></tr></tbody>
          </table><div v-else class="empty"><div class="empty-text">暂无质量标准</div></div></div>
          <div v-else class="table-wrap"><table v-if="plans.length" class="data-table qm-wide"><thead><tr><th>方案名称</th><th>关联标准</th><th>适用范围</th><th>触发方式</th><th>检验类型</th><th>抽样</th><th>频次</th><th>门禁</th><th>时限</th><th>状态</th><th>操作</th></tr></thead>
            <tbody><tr v-for="row in plans" :key="row.id"><td>{{ row.name }}</td><td>{{ row.standard_no || '-' }}</td><td>{{ scopeLabel(row) }}</td><td>{{ triggerLabel(row.trigger_type) }}</td><td>{{ typeLabel(row.inspection_type) }}</td><td>{{ samplingLabel(row) }}</td><td>{{ row.frequency_qty || '-' }}</td><td>{{ gateLabel(row.gate_mode) }}</td><td>{{ row.due_minutes }} 分钟</td><td><span class="badge" :class="row.status==='active'?'badge-success':'badge-info'">{{ row.status==='active'?'启用':'停用' }}</span></td><td class="qm-row-actions"><button v-if="canPlans" class="btn btn-default btn-sm" @click="editPlan(row)">编辑</button><button v-if="canPlans && row.status==='active'" class="btn btn-danger btn-sm" @click="archivePlan(row)">停用</button></td></tr></tbody>
          </table><div v-else class="empty"><div class="empty-text">暂无检验方案</div></div></div>
        </section>

        <section v-else-if="activeTab==='ncr' || activeTab==='capa'">
          <div class="qm-segments"><button class="tab-btn" :class="{active:activeTab==='ncr'}" @click="switchTab('ncr')">不合格单</button><button class="tab-btn" :class="{active:activeTab==='capa'}" @click="switchTab('capa')">CAPA</button></div>
          <div v-if="activeTab==='ncr'" class="table-wrap"><table v-if="ncrItems.length" class="data-table qm-wide"><thead><tr><th>不合格单</th><th>来源</th><th>订单/供应商</th><th>工序/物料</th><th>缺陷</th><th>数量</th><th>处置</th><th>负责人</th><th>状态</th><th>要求完成</th><th>操作</th></tr></thead>
            <tbody><tr v-for="row in ncrItems" :key="row.id"><td><code>{{ row.ncr_no }}</code></td><td>{{ sourceLabel(row.source_type) }}</td><td>{{ row.order_no || row.supplier_name || '-' }}</td><td>{{ row.process_name || row.material_name || '-' }}</td><td>{{ defectLevelLabel(row.defect_level) }}<div class="cell-muted">{{ row.defect_category || row.description || '-' }}</div></td><td>{{ row.defect_quantity }}</td><td>{{ dispositionLabel(row.disposition) }}</td><td>{{ row.owner_name || row.responsible_user_name || '-' }}</td><td><span class="badge" :class="statusClass(row.status)">{{ ncrStatusLabel(row.status) }}</span></td><td>{{ row.due_at || '-' }}</td><td class="qm-row-actions"><button v-if="canDisposition && !['closed','cancelled'].includes(row.status)" class="btn btn-primary btn-sm" @click="openDisposition(row)">处置</button><button v-if="canCapa" class="btn btn-default btn-sm" @click="openCapa(null,row)">建CAPA</button></td></tr></tbody>
          </table><div v-else class="empty"><div class="empty-text">暂无不合格单</div></div></div>
          <div v-else class="table-wrap"><table v-if="capaItems.length" class="data-table qm-wide"><thead><tr><th>CAPA编号</th><th>标题</th><th>来源NCR</th><th>根因</th><th>纠正/预防措施</th><th>负责人</th><th>到期日</th><th>状态</th><th>效果验证</th><th>操作</th></tr></thead>
            <tbody><tr v-for="row in capaItems" :key="row.id" :class="{'qm-overdue-row':row.overdue}"><td><code>{{ row.capa_no }}</code></td><td>{{ row.title }}</td><td><code>{{ row.ncr_no || '-' }}</code></td><td>{{ row.root_cause || '-' }}</td><td>{{ row.corrective_action || '-' }}<div class="cell-muted">{{ row.preventive_action || '-' }}</div></td><td>{{ row.owner_name || '-' }}</td><td>{{ row.due_at || '-' }}</td><td><span class="badge" :class="statusClass(row.status)">{{ capaStatusLabel(row.status) }}</span></td><td>{{ row.effectiveness_result || '-' }}</td><td><button v-if="canCapa" class="btn btn-default btn-sm" @click="openCapa(row)">编辑</button></td></tr></tbody>
          </table><div v-else class="empty"><div class="empty-text">暂无 CAPA 记录</div></div></div>
        </section>

        <section v-else-if="activeTab==='suppliers' || activeTab==='gauges'">
          <div class="qm-segments"><button class="tab-btn" :class="{active:activeTab==='suppliers'}" @click="switchTab('suppliers')">供应商质量</button><button class="tab-btn" :class="{active:activeTab==='gauges'}" @click="switchTab('gauges')">量具校准</button></div>
          <template v-if="activeTab==='suppliers'">
            <div class="table-wrap qm-summary-table"><table v-if="supplierStats.length" class="data-table"><thead><tr><th>供应商</th><th>检验批次</th><th>检验数量</th><th>不合格数量</th><th>批次合格率</th><th>平均分</th></tr></thead><tbody><tr v-for="row in supplierStats" :key="row.supplier_id"><td>{{ row.supplier_name }}</td><td>{{ row.inspection_count }}</td><td>{{ row.checked_qty }}</td><td>{{ row.failed_qty }}</td><td>{{ supplierPassRate(row) }}%</td><td>{{ row.avg_score || '-' }}</td></tr></tbody></table></div>
            <div class="table-wrap"><table v-if="supplierInspections.length" class="data-table qm-wide"><thead><tr><th>检验时间</th><th>供应商</th><th>物料</th><th>批次/送货单</th><th>检验数量</th><th>判定</th><th>评分</th><th>缺陷</th><th>检验员</th><th>NCR</th></tr></thead><tbody><tr v-for="row in supplierInspections" :key="row.id"><td>{{ row.inspected_at }}</td><td>{{ row.supplier_name }}</td><td>{{ row.material_name || '-' }}</td><td>{{ row.batch_no || '-' }}<div class="cell-muted">{{ row.delivery_no || '-' }}</div></td><td>{{ row.quantity_checked }} / 不合格 {{ row.quantity_failed }}</td><td><span class="badge" :class="resultClass(row.result)">{{ resultLabel(row.result) }}</span></td><td>{{ row.score_total || '-' }}</td><td>{{ defectLevelLabel(row.defect_level) }}<div class="cell-muted">{{ row.defect_category || '-' }}</div></td><td>{{ row.inspector_name || '-' }}</td><td><code>{{ row.ncr_no || '-' }}</code></td></tr></tbody></table><div v-else class="empty"><div class="empty-text">暂无来料检验记录</div></div></div>
          </template>
          <div v-else class="table-wrap"><table v-if="gauges.length" class="data-table qm-wide"><thead><tr><th>量具编号</th><th>名称/型号</th><th>量程/精度</th><th>存放位置</th><th>负责人</th><th>校准周期</th><th>上次校准</th><th>下次校准</th><th>证书号</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in gauges" :key="row.id" :class="{'qm-overdue-row':row.overdue}"><td><code>{{ row.gauge_no }}</code></td><td>{{ row.name }}<div class="cell-muted">{{ row.model || '-' }}</div></td><td>{{ row.measurement_range || '-' }}<div class="cell-muted">{{ row.accuracy || '-' }}</div></td><td>{{ row.location || '-' }}</td><td>{{ row.owner_name || '-' }}</td><td>{{ row.calibration_cycle_days }} 天</td><td>{{ row.last_calibrated_at || '-' }}</td><td>{{ row.next_calibration_at || '-' }}<div v-if="row.overdue" class="cell-muted text-danger">已逾期</div></td><td>{{ row.certificate_no || '-' }}</td><td><span class="badge" :class="row.status==='active'?'badge-success':'badge-danger'">{{ gaugeStatusLabel(row.status) }}</span></td><td class="qm-row-actions"><button v-if="canCalibration" class="btn btn-default btn-sm" @click="openGauge(row)">编辑</button><button v-if="canCalibration" class="btn btn-primary btn-sm" @click="openCalibration(row)">校准</button></td></tr></tbody></table><div v-else class="empty"><div class="empty-text">暂无量具</div></div></div>
        </section>

        <section v-else-if="activeTab==='analytics'" class="qm-analytics">
          <div class="qm-date-filter"><input v-model="dateFrom" type="date" class="form-input"><span>至</span><input v-model="dateTo" type="date" class="form-input"><button class="btn btn-default btn-sm" @click="loadAnalytics">查询</button></div>
          <div class="qm-section-head"><h4>质量趋势</h4></div>
          <div class="table-wrap"><table v-if="analytics.trend?.length" class="data-table"><thead><tr><th>日期</th><th>检验数量</th><th>不合格数量</th><th>合格率</th><th>平均分</th></tr></thead><tbody><tr v-for="row in analytics.trend" :key="row.date"><td>{{ row.date }}</td><td>{{ row.checked }}</td><td>{{ row.failed }}</td><td>{{ passRate(row.checked,row.failed) }}%</td><td>{{ row.avg_score || '-' }}</td></tr></tbody></table></div>
          <div class="qm-analytics-grid">
            <section><div class="qm-section-head"><h4>缺陷 Pareto</h4></div><table v-if="analytics.pareto?.length" class="data-table"><thead><tr><th>缺陷</th><th>记录</th><th>数量</th></tr></thead><tbody><tr v-for="row in analytics.pareto" :key="row.category"><td>{{ row.category }}</td><td>{{ row.records }}</td><td>{{ row.quantity }}</td></tr></tbody></table></section>
            <section><div class="qm-section-head"><h4>工序质量</h4></div><table v-if="analytics.processes?.length" class="data-table"><thead><tr><th>工序</th><th>检验</th><th>不合格</th><th>平均分</th></tr></thead><tbody><tr v-for="row in analytics.processes" :key="row.process_id"><td>{{ row.process_name }}</td><td>{{ row.inspections }}</td><td>{{ row.failed }}</td><td>{{ row.avg_score || '-' }}</td></tr></tbody></table></section>
          </div>
        </section>

        <section v-else class="qm-rules">
          <div class="qm-rule-grid">
            <label><span>质量管理</span><input v-model="ruleForm.enabled" type="checkbox"></label>
            <label><span>自动生成首件任务</span><input v-model="ruleForm.auto_first_article" type="checkbox"></label>
            <label><span>自动生成完工检验</span><input v-model="ruleForm.auto_final_inspection" type="checkbox"></label>
            <label><span>自动生成出库检验</span><input v-model="ruleForm.auto_outgoing_inspection" type="checkbox"></label>
            <label><span>低分评价生成核验任务</span><input v-model="ruleForm.low_evaluation_creates_task" type="checkbox"></label>
            <label><span>首件门禁</span><select v-model="ruleForm.first_article_gate" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label>
            <label><span>过程检验门禁</span><select v-model="ruleForm.in_process_gate" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label>
            <label><span>完工检验门禁</span><select v-model="ruleForm.final_gate" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label>
            <label><span>出库检验门禁</span><select v-model="ruleForm.shipment_gate" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label>
            <label><span>默认过程抽检频次</span><input v-model.number="ruleForm.in_process_frequency" type="number" min="1" class="form-input"></label>
            <label><span>重复问题 CAPA 阈值</span><input v-model.number="ruleForm.capa_repeat_threshold" type="number" min="1" class="form-input"></label>
            <label><span>量具到期预警天数</span><input v-model.number="ruleForm.gauge_due_warning_days" type="number" min="0" class="form-input"></label>
          </div>
          <button v-if="canStandards" class="btn btn-primary" @click="saveRules">保存规则</button>
        </section>
      </div>
    </div>

    <div v-if="showStandard" class="modal-overlay"><div class="modal qm-modal qm-modal-wide"><div class="modal-header"><span>{{ standardForm.id ? '编辑质量标准' : '新增质量标准' }}</span><span class="modal-close" @click="showStandard=false">&times;</span></div><div class="modal-body">
      <div class="qm-form-grid"><label>标准编码<input v-model="standardForm.standard_no" class="form-input"></label><label>标准名称<input v-model="standardForm.name" class="form-input"></label><label>检验类型<select v-model="standardForm.inspection_type" class="form-input"><option v-for="option in inspectionTypeOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label>版本<input v-model.number="standardForm.version" type="number" min="1" class="form-input"></label><label>产品编码<input v-model="standardForm.product_code" class="form-input" list="qm-product-codes"><datalist id="qm-product-codes"><option v-for="p in refs.products" :key="p.id" :value="p.product_code">{{ p.product_name }}</option></datalist></label><label>工序路线<select v-model="standardForm.route_id" class="form-input"><option :value="null">全部路线</option><option v-for="r in refs.routes" :key="r.id" :value="r.id">{{ r.name }}</option></select></label><label>工序<select v-model="standardForm.process_id" class="form-input"><option :value="null">全部工序</option><option v-for="p in refs.processes" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>门禁<select v-model="standardForm.gate_mode" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label><label>抽样方式<select v-model="standardForm.sampling_mode" class="form-input"><option value="fixed">固定数量</option><option value="ratio">比例</option><option value="full">全检</option></select></label><label>抽样值<input v-model.number="standardForm.sample_value" type="number" min="0.01" step="0.01" class="form-input"></label><label>最低分<input v-model.number="standardForm.min_score" type="number" min="0" max="100" class="form-input"></label><label>状态<select v-model="standardForm.status" class="form-input"><option value="active">启用</option><option value="draft">草稿</option><option value="inactive">停用</option></select></label></div>
      <label class="qm-full-label">备注<textarea v-model="standardForm.notes" rows="2" class="form-input"></textarea></label>
      <div class="qm-section-head"><h4>检验项目</h4><button class="btn btn-default btn-sm" @click="addStandardItem">新增项目</button></div>
      <div class="table-wrap"><table class="data-table qm-item-table"><thead><tr><th>编码</th><th>项目名称</th><th>类型</th><th>单位</th><th>标准值</th><th>下限</th><th>上限</th><th>权重</th><th>必检</th><th></th></tr></thead><tbody><tr v-for="(item,index) in standardForm.items" :key="index"><td><input v-model="item.item_code" class="form-input"></td><td><input v-model="item.item_name" class="form-input"></td><td><select v-model="item.item_type" class="form-input"><option value="numeric">数值</option><option value="boolean">判定</option><option value="score">评分</option><option value="text">文本</option></select></td><td><input v-model="item.unit" class="form-input"></td><td><input v-model="item.nominal_value" class="form-input"></td><td><input v-model="item.lower_limit" class="form-input"></td><td><input v-model="item.upper_limit" class="form-input"></td><td><input v-model.number="item.weight" type="number" min="0" class="form-input"></td><td><input v-model="item.required" type="checkbox"></td><td><button class="btn btn-danger btn-sm" @click="standardForm.items.splice(index,1)">删除</button></td></tr></tbody></table></div>
    </div><div class="modal-footer"><button class="btn btn-default" @click="showStandard=false">取消</button><button class="btn btn-primary" @click="saveStandard">保存</button></div></div></div>

    <div v-if="showPlan" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>{{ planForm.id ? '编辑检验方案' : '新增检验方案' }}</span><span class="modal-close" @click="showPlan=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>方案名称<input v-model="planForm.name" class="form-input"></label><label>质量标准<select v-model="planForm.standard_id" class="form-input"><option :value="null">不关联</option><option v-for="s in standards" :key="s.id" :value="s.id">{{ s.standard_no }} - {{ s.name }}</option></select></label><label>触发方式<select v-model="planForm.trigger_type" class="form-input"><option v-for="option in triggerOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label>检验类型<select v-model="planForm.inspection_type" class="form-input"><option v-for="option in inspectionTypeOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label>产品编码<input v-model="planForm.product_code" class="form-input"></label><label>工序路线<select v-model="planForm.route_id" class="form-input"><option :value="null">全部路线</option><option v-for="r in refs.routes" :key="r.id" :value="r.id">{{ r.name }}</option></select></label><label>工序<select v-model="planForm.process_id" class="form-input"><option :value="null">全部工序</option><option v-for="p in refs.processes" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>门禁<select v-model="planForm.gate_mode" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label><label>抽样方式<select v-model="planForm.sampling_mode" class="form-input"><option value="fixed">固定数量</option><option value="ratio">比例</option><option value="full">全检</option></select></label><label>抽样值<input v-model.number="planForm.sample_value" type="number" min="0.01" step="0.01" class="form-input"></label><label>数量频次<input v-model.number="planForm.frequency_qty" type="number" min="0" class="form-input"></label><label>检验时限(分钟)<input v-model.number="planForm.due_minutes" type="number" min="1" class="form-input"></label><label>状态<select v-model="planForm.status" class="form-input"><option value="active">启用</option><option value="inactive">停用</option></select></label></div></div><div class="modal-footer"><button class="btn btn-default" @click="showPlan=false">取消</button><button class="btn btn-primary" @click="savePlan">保存</button></div></div></div>

    <div v-if="showTask" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>新增检验任务</span><span class="modal-close" @click="showTask=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>订单<select v-model="taskForm.order_id" class="form-input"><option :value="null">请选择</option><option v-for="o in refs.orders" :key="o.id" :value="o.id">{{ o.order_no }} - {{ o.product_name }}</option></select></label><label>工序<select v-model="taskForm.process_id" class="form-input"><option :value="null">请选择</option><option v-for="p in refs.processes" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>检验类型<select v-model="taskForm.inspection_type" class="form-input"><option v-for="option in inspectionTypeOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label>质量标准<select v-model="taskForm.standard_id" class="form-input"><option :value="null">不关联</option><option v-for="s in standards" :key="s.id" :value="s.id">{{ s.standard_no }} - {{ s.name }}</option></select></label><label>序列号<input v-model="taskForm.serial_no" class="form-input"></label><label>批次号<input v-model="taskForm.batch_no" class="form-input"></label><label>抽样数量<input v-model.number="taskForm.sample_qty" type="number" min="1" class="form-input"></label><label>门禁<select v-model="taskForm.gate_mode" class="form-input"><option value="hard">强拦截</option><option value="soft">软提示</option><option value="off">关闭</option></select></label><label>优先级<select v-model="taskForm.priority" class="form-input"><option value="normal">普通</option><option value="urgent">紧急</option></select></label><label>负责人<select v-model="taskForm.assigned_to" class="form-input"><option :value="null">未分配</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label></div></div><div class="modal-footer"><button class="btn btn-default" @click="showTask=false">取消</button><button class="btn btn-primary" @click="saveTask">创建</button></div></div></div>

    <div v-if="showInspection" class="modal-overlay"><div class="modal qm-modal qm-modal-wide"><div class="modal-header"><span>执行检验 - {{ inspectionTask?.task_no }}</span><span class="modal-close" @click="showInspection=false">&times;</span></div><div class="modal-body"><div class="qm-inspection-meta"><span>{{ inspectionTask?.order_no || inspectionTask?.shipment_no }}</span><span>{{ inspectionTask?.process_name }}</span><span>{{ inspectionTask?.standard_no || '无标准' }}</span><span>抽样 {{ inspectionTask?.sample_qty }}</span></div>
      <div class="table-wrap" v-if="inspectionForm.measurements.length"><table class="data-table qm-item-table"><thead><tr><th>检验项目</th><th>标准</th><th>实测/判定</th><th>备注</th></tr></thead><tbody><tr v-for="m in inspectionForm.measurements" :key="m.item_id"><td>{{ m.item_name }}<div class="cell-muted">{{ m.item_code }}</div></td><td>{{ measurementStandard(m) }}</td><td><select v-if="m.item_type==='boolean'" v-model="m.value" class="form-input"><option :value="true">合格</option><option :value="false">不合格</option></select><input v-else v-model="m.value" :type="m.item_type==='score'||m.item_type==='numeric'?'number':'text'" class="form-input" :max="m.item_type==='score'?m.weight:null"></td><td><input v-model="m.note" class="form-input"></td></tr></tbody></table></div>
      <div class="qm-form-grid qm-inspection-form"><label>检验数量<input v-model.number="inspectionForm.quantity_checked" type="number" min="1" class="form-input"></label><label>不合格数量<input v-model.number="inspectionForm.quantity_failed" type="number" min="0" class="form-input"></label><label>最终判定<select v-model="inspectionForm.result" class="form-input"><option value="pass">合格</option><option value="rework">返修</option><option value="scrap">报废</option></select></label><label>缺陷等级<select v-model="inspectionForm.defect_level" class="form-input"><option value="">无</option><option value="minor">轻微</option><option value="general">一般</option><option value="severe">严重</option><option value="critical">致命</option></select></label><label>缺陷分类<input v-model="inspectionForm.defect_category" class="form-input"></label><label>责任工序<select v-model="inspectionForm.responsible_process_id" class="form-input"><option :value="null">当前工序</option><option v-for="p in refs.processes" :key="p.id" :value="p.id">{{ p.name }}</option></select></label></div><label class="qm-full-label">检验备注<textarea v-model="inspectionForm.notes" rows="3" class="form-input"></textarea></label>
    </div><div class="modal-footer"><button class="btn btn-default" @click="showInspection=false">取消</button><button class="btn btn-primary" @click="submitInspection">提交检验</button></div></div></div>

    <div v-if="showDisposition" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>不合格处置 - {{ dispositionRow?.ncr_no }}</span><span class="modal-close" @click="showDisposition=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>处置方式<select v-model="dispositionForm.disposition" class="form-input"><option value="rework">返修</option><option value="scrap">报废</option><option value="concession">让步接收</option><option value="isolate">继续隔离</option><option value="return">退回</option></select></label><label>负责人<select v-model="dispositionForm.owner_id" class="form-input"><option :value="null">未分配</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label><label>责任人员<select v-model="dispositionForm.responsible_user_id" class="form-input"><option :value="null">未指定</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label><label>责任工序<select v-model="dispositionForm.responsible_process_id" class="form-input"><option :value="null">未指定</option><option v-for="p in refs.processes" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>要求完成<input v-model="dispositionForm.due_at" type="date" class="form-input"></label></div><label class="qm-full-label">根因<textarea v-model="dispositionForm.root_cause" rows="2" class="form-input"></textarea></label><label class="qm-full-label">纠正措施<textarea v-model="dispositionForm.corrective_action" rows="2" class="form-input"></textarea></label><label class="qm-full-label">处置说明<textarea v-model="dispositionForm.note" rows="2" class="form-input"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showDisposition=false">取消</button><button class="btn btn-primary" @click="saveDisposition">确认处置</button></div></div></div>

    <div v-if="showCapa" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>{{ capaForm.id ? '编辑 CAPA' : '新增 CAPA' }}</span><span class="modal-close" @click="showCapa=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>来源NCR<select v-model="capaForm.ncr_id" class="form-input"><option :value="null">无</option><option v-for="n in ncrItems" :key="n.id" :value="n.id">{{ n.ncr_no }}</option></select></label><label>标题<input v-model="capaForm.title" class="form-input"></label><label>负责人<select v-model="capaForm.owner_id" class="form-input"><option :value="null">未分配</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label><label>到期日<input v-model="capaForm.due_at" type="date" class="form-input"></label><label>状态<select v-model="capaForm.status" class="form-input"><option value="open">待分析</option><option value="processing">执行中</option><option value="verified">已验证</option><option value="closed">已关闭</option></select></label></div><label class="qm-full-label">问题描述<textarea v-model="capaForm.problem_description" rows="2" class="form-input"></textarea></label><label class="qm-full-label">根因分析<textarea v-model="capaForm.root_cause" rows="2" class="form-input"></textarea></label><label class="qm-full-label">纠正措施<textarea v-model="capaForm.corrective_action" rows="2" class="form-input"></textarea></label><label class="qm-full-label">预防措施<textarea v-model="capaForm.preventive_action" rows="2" class="form-input"></textarea></label><label class="qm-full-label">效果验证<textarea v-model="capaForm.effectiveness_result" rows="2" class="form-input"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showCapa=false">取消</button><button class="btn btn-primary" @click="saveCapa">保存</button></div></div></div>

    <div v-if="showSupplier" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>新增来料检验</span><span class="modal-close" @click="showSupplier=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>供应商<select v-model="supplierForm.supplier_id" class="form-input"><option :value="null">请选择</option><option v-for="s in refs.suppliers" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label>物料<select v-model="supplierForm.material_id" class="form-input"><option :value="null">请选择</option><option v-for="m in refs.materials" :key="m.id" :value="m.id">{{ m.name }} {{ m.spec }}</option></select></label><label>批次号<input v-model="supplierForm.batch_no" class="form-input"></label><label>送货单号<input v-model="supplierForm.delivery_no" class="form-input"></label><label>检验数量<input v-model.number="supplierForm.quantity_checked" type="number" min="1" class="form-input"></label><label>不合格数量<input v-model.number="supplierForm.quantity_failed" type="number" min="0" class="form-input"></label><label>判定<select v-model="supplierForm.result" class="form-input"><option value="pass">合格</option><option value="rework">挑选/返工</option><option value="scrap">报废</option><option value="return">退货</option></select></label><label>评分<input v-model.number="supplierForm.score_total" type="number" min="0" max="100" class="form-input"></label><label>缺陷等级<select v-model="supplierForm.defect_level" class="form-input"><option value="">无</option><option value="minor">轻微</option><option value="general">一般</option><option value="severe">严重</option><option value="critical">致命</option></select></label><label>缺陷分类<input v-model="supplierForm.defect_category" class="form-input"></label></div><label class="qm-full-label">备注<textarea v-model="supplierForm.notes" rows="3" class="form-input"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showSupplier=false">取消</button><button class="btn btn-primary" @click="saveSupplierInspection">保存</button></div></div></div>

    <div v-if="showGauge" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>{{ gaugeForm.id ? '编辑量具' : '新增量具' }}</span><span class="modal-close" @click="showGauge=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>量具编号<input v-model="gaugeForm.gauge_no" class="form-input"></label><label>名称<input v-model="gaugeForm.name" class="form-input"></label><label>型号<input v-model="gaugeForm.model" class="form-input"></label><label>量程<input v-model="gaugeForm.measurement_range" class="form-input"></label><label>精度<input v-model="gaugeForm.accuracy" class="form-input"></label><label>存放位置<input v-model="gaugeForm.location" class="form-input"></label><label>校准周期(天)<input v-model.number="gaugeForm.calibration_cycle_days" type="number" min="1" class="form-input"></label><label>负责人<select v-model="gaugeForm.owner_id" class="form-input"><option :value="null">未分配</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label><label>状态<select v-model="gaugeForm.status" class="form-input"><option value="active">在用</option><option value="suspended">停用</option><option value="scrapped">报废</option></select></label></div><label class="qm-full-label">备注<textarea v-model="gaugeForm.remark" rows="2" class="form-input"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showGauge=false">取消</button><button class="btn btn-primary" @click="saveGauge">保存</button></div></div></div>

    <div v-if="showCalibration" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>量具校准 - {{ calibrationGauge?.gauge_no }}</span><span class="modal-close" @click="showCalibration=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>校准日期<input v-model="calibrationForm.calibrated_at" type="date" class="form-input"></label><label>下次校准<input v-model="calibrationForm.next_calibration_at" type="date" class="form-input"></label><label>结果<select v-model="calibrationForm.result" class="form-input"><option value="pass">合格</option><option value="fail">不合格</option></select></label><label>证书号<input v-model="calibrationForm.certificate_no" class="form-input"></label><label>校准机构<input v-model="calibrationForm.organization" class="form-input"></label></div><label class="qm-full-label">备注<textarea v-model="calibrationForm.notes" rows="2" class="form-input"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showCalibration=false">取消</button><button class="btn btn-primary" @click="saveCalibration">保存校准</button></div></div></div>

    <div v-if="showReview" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>审核检验记录</span><span class="modal-close" @click="showReview=false">&times;</span></div><div class="modal-body"><div class="qm-inspection-meta"><span>{{ reviewRow?.task_no || ('检验记录 #' + reviewRow?.id) }}</span><span>{{ reviewRow?.order_no || '-' }}</span><span>{{ reviewRow?.result }}</span><span>评分 {{ reviewRow?.score_total || '-' }}</span></div><div class="qm-form-grid"><label>审核结果<select v-model="reviewForm.status" class="form-input"><option value="approved">审核通过</option><option value="rejected">驳回并生成异常</option></select></label></div><label class="qm-full-label">审核意见<textarea v-model="reviewForm.note" rows="4" class="form-input" placeholder="驳回时必须填写原因"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showReview=false">取消</button><button class="btn btn-primary" @click="saveReview">提交审核</button></div></div></div>

    <div v-if="showNcr" class="modal-overlay"><div class="modal qm-modal"><div class="modal-header"><span>新增质量异常</span><span class="modal-close" @click="showNcr=false">&times;</span></div><div class="modal-body"><div class="qm-form-grid"><label>订单<select v-model="ncrForm.order_id" class="form-input"><option :value="null">不关联订单</option><option v-for="o in refs.orders" :key="o.id" :value="o.id">{{ o.order_no }} - {{ o.product_name }}</option></select></label><label>工序<select v-model="ncrForm.process_id" class="form-input"><option :value="null">不关联工序</option><option v-for="p in refs.processes" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>缺陷等级<select v-model="ncrForm.defect_level" class="form-input"><option value="minor">轻微</option><option value="general">一般</option><option value="severe">严重</option><option value="critical">致命</option></select></label><label>缺陷数量<input v-model.number="ncrForm.defect_quantity" type="number" min="1" class="form-input"></label><label>缺陷分类<input v-model="ncrForm.defect_category" class="form-input"></label><label>责任人员<select v-model="ncrForm.responsible_user_id" class="form-input"><option :value="null">未指定</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label><label>负责人<select v-model="ncrForm.owner_id" class="form-input"><option :value="null">未指定</option><option v-for="u in refs.users" :key="u.id" :value="u.id">{{ u.name }}</option></select></label><label>要求完成<input v-model="ncrForm.due_at" type="date" class="form-input"></label></div><label class="qm-full-label">问题描述<textarea v-model="ncrForm.description" rows="4" class="form-input"></textarea></label></div><div class="modal-footer"><button class="btn btn-default" @click="showNcr=false">取消</button><button class="btn btn-primary" @click="saveNcr">创建异常</button></div></div></div>

    <div v-if="showNcrDetail" class="modal-overlay"><div class="modal qm-modal qm-modal-wide"><div class="modal-header"><span>质量异常详情 - {{ ncrDetail?.ncr_no }}</span><span class="modal-close" @click="showNcrDetail=false">&times;</span></div><div class="modal-body"><div class="qm-inspection-meta"><span>{{ ncrDetail?.order_no || ncrDetail?.supplier_name || '未关联对象' }}</span><span>{{ ncrDetail?.process_name || ncrDetail?.material_name || '-' }}</span><span>{{ defectLevelLabel(ncrDetail?.defect_level) }}</span><span>{{ ncrStatusLabel(ncrDetail?.status) }}</span></div><p>{{ ncrDetail?.description || '-' }}</p><div class="qm-section-head"><h4>处理轨迹</h4></div><div v-if="ncrDetail?.actions?.length" class="qm-timeline"><div v-for="action in ncrDetail.actions" :key="action.created_at + action.action" class="qm-timeline-item"><strong>{{ action.action }}</strong><span>{{ action.actor_name || '系统' }} · {{ action.created_at }}</span><div>{{ action.note || '-' }}</div></div></div><div v-else class="empty"><div class="empty-text">暂无处理记录</div></div></div><div class="modal-footer"><button class="btn btn-default" @click="showNcrDetail=false">关闭</button></div></div></div>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { api } from '@/lib/api.js'
import { can } from '@/lib/auth.js'
import { showToast } from '@/lib/store.js'

const tabs = [
  { key:'overview', label:'质量工作台' }, { key:'tasks', label:'检验任务' }, { key:'records', label:'检验记录' },
  { key:'standards', label:'标准方案' }, { key:'ncr', label:'不合格品' }, { key:'capa', label:'CAPA' },
  { key:'suppliers', label:'质量资源' }, { key:'analytics', label:'统计分析' }, { key:'rules', label:'门禁规则', permission:'quality:standards' },
]
const inspectionTypeOptions = [
  {value:'first_article',label:'首件检验'},{value:'in_process',label:'过程检验'},{value:'final',label:'完工检验'},
  {value:'outgoing',label:'出库检验'},{value:'rework_check',label:'返修复检'},{value:'quality_verification',label:'质量核验'},{value:'manual',label:'手工检验'},
]
const triggerOptions = [
  {value:'first_report',label:'首件报工'},{value:'quantity_interval',label:'数量间隔'},{value:'final_process',label:'最终工序完成'},
  {value:'shipment',label:'创建出库单'},{value:'rework_complete',label:'返修完成'},{value:'low_evaluation',label:'低分工序评价'},{value:'manual',label:'手工创建'},
]
const visibleTabs = computed(() => tabs.filter(tab => !tab.permission || can(tab.permission)))
const canInspect = computed(() => can('quality:inspect') || can('quality:edit'))
const canStandards = computed(() => can('quality:standards'))
const canPlans = computed(() => can('quality:plans'))
const canDisposition = computed(() => can('quality:disposition'))
const canReview = computed(() => can('quality:review') || can('quality:edit'))
const canCapa = computed(() => can('quality:capa'))
const canSupplier = computed(() => can('quality:supplier'))
const canCalibration = computed(() => can('quality:calibration'))
const activeTab = ref(localStorage.getItem('qualityManagementTab') || 'overview')
const standardMode = ref('standards')
const keyword = ref('')
const filterStatus = ref('')
const dateFrom = ref(new Date(Date.now()-30*86400000).toISOString().slice(0,10))
const dateTo = ref(new Date().toISOString().slice(0,10))
const dashboard = ref({})
const refs = reactive({ orders:[], products:[], routes:[], processes:[], users:[], suppliers:[], materials:[] })
const tasks = ref([]), records = ref([]), standards = ref([]), plans = ref([]), ncrItems = ref([]), capaItems = ref([])
const supplierInspections = ref([]), supplierStats = ref([]), gauges = ref([]), analytics = ref({})
const ruleForm = reactive({})

const showStandard=ref(false), showPlan=ref(false), showTask=ref(false), showInspection=ref(false), showDisposition=ref(false)
const showCapa=ref(false), showSupplier=ref(false), showGauge=ref(false), showCalibration=ref(false)
const showReview=ref(false), showNcr=ref(false), showNcrDetail=ref(false)
const inspectionTask=ref(null), dispositionRow=ref(null), calibrationGauge=ref(null)
const reviewRow=ref(null), ncrDetail=ref(null)
const standardForm=reactive({}), planForm=reactive({}), taskForm=reactive({}), inspectionForm=reactive({measurements:[]})
const dispositionForm=reactive({}), capaForm=reactive({}), supplierForm=reactive({}), gaugeForm=reactive({}), calibrationForm=reactive({})
const reviewForm=reactive({status:'approved',note:''})
const ncrForm=reactive({order_id:null,process_id:null,defect_level:'general',defect_quantity:1,defect_category:'',description:'',responsible_user_id:null,owner_id:null,due_at:''})

const primaryLabel = computed(() => {
  if (activeTab.value==='tasks' && canInspect.value) return '新增任务'
  if (activeTab.value==='standards' && standardMode.value==='standards' && canStandards.value) return '新增标准'
  if (activeTab.value==='standards' && standardMode.value==='plans' && canPlans.value) return '新增方案'
  if (activeTab.value==='capa' && canCapa.value) return '新增 CAPA'
  if (activeTab.value==='suppliers' && canSupplier.value) return '新增来料检验'
  if (activeTab.value==='gauges' && canCalibration.value) return '新增量具'
  if (activeTab.value==='ncr' && canDisposition.value) return '新增质量异常'
  return ''
})

async function loadRefs(){ try{Object.assign(refs,await api.domains.qualityManagement.qualityReferences())}catch(e){showToast(e.message||'基础数据加载失败','error')} }
async function loadDashboard(){ dashboard.value=await api.domains.qualityManagement.qualityDashboard() }
async function loadTasks(){ const d=await api.domains.qualityManagement.qualityTasks({keyword:keyword.value,status:filterStatus.value,limit:500});tasks.value=d.items||[] }
async function loadRecords(){ const d=await api.domains.qualityManagement.managedInspections({keyword:keyword.value,result:filterStatus.value,limit:500});records.value=d.items||[] }
async function loadStandards(){ const d=await api.domains.qualityManagement.qualityStandards({keyword:keyword.value,limit:500});standards.value=d.items||[] }
async function loadPlans(){ const d=await api.domains.qualityManagement.qualityPlans({keyword:keyword.value,limit:500});plans.value=d.items||[] }
async function loadNcr(){ const d=await api.domains.qualityManagement.qualityNcr({keyword:keyword.value,status:filterStatus.value,limit:500});ncrItems.value=d.items||[] }
async function loadCapa(){ const d=await api.domains.qualityManagement.qualityCapa({keyword:keyword.value,status:filterStatus.value,limit:500});capaItems.value=d.items||[] }
async function loadSuppliers(){ const d=await api.domains.qualityManagement.supplierInspections({keyword:keyword.value,result:filterStatus.value,limit:500});supplierInspections.value=d.items||[];supplierStats.value=d.supplier_stats||[] }
async function loadGauges(){ const d=await api.domains.qualityManagement.qualityGauges({keyword:keyword.value,status:filterStatus.value,limit:500});gauges.value=d.items||[] }
async function loadAnalytics(){ analytics.value=await api.domains.qualityManagement.qualityAnalytics({from:dateFrom.value,to:dateTo.value}) }
async function loadRules(){ Object.assign(ruleForm,await api.domains.qualityManagement.qualityRules()) }
async function loadActive(){
  try{
    if(activeTab.value==='overview')await loadDashboard()
    if(activeTab.value==='tasks')await loadTasks()
    if(activeTab.value==='records')await loadRecords()
    if(activeTab.value==='standards'){await loadStandards();await loadPlans()}
    if(activeTab.value==='ncr')await loadNcr()
    if(activeTab.value==='capa')await loadCapa()
    if(activeTab.value==='suppliers')await loadSuppliers()
    if(activeTab.value==='gauges')await loadGauges()
    if(activeTab.value==='analytics')await loadAnalytics()
    if(activeTab.value==='rules')await loadRules()
    if(activeTab.value!=='overview')await loadDashboard()
  }catch(e){showToast(e.message||'质量数据加载失败','error')}
}
async function switchTab(key){activeTab.value=key;filterStatus.value='';keyword.value='';localStorage.setItem('qualityManagementTab',key);await loadActive()}
function openPrimary(){if(activeTab.value==='tasks')openTask();else if(activeTab.value==='standards'&&standardMode.value==='standards')openStandard();else if(activeTab.value==='standards')openPlan();else if(activeTab.value==='capa')openCapa();else if(activeTab.value==='suppliers')openSupplier();else if(activeTab.value==='gauges')openGauge();else if(activeTab.value==='ncr')openNcr()}
function openReview(row){reviewRow.value=row;Object.assign(reviewForm,{status:'approved',note:''});showReview.value=true}
async function saveReview(){try{await api.domains.qualityManagement.reviewQualityInspection(reviewRow.value.id,{...reviewForm});showReview.value=false;showToast('检验审核已保存');await loadRecords();await loadDashboard()}catch(e){showToast(e.message||'审核失败','error')}}
function openNcr(){Object.assign(ncrForm,{order_id:null,process_id:null,defect_level:'general',defect_quantity:1,defect_category:'',description:'',responsible_user_id:null,owner_id:null,due_at:''});showNcr.value=true}
async function saveNcr(){try{await api.domains.qualityManagement.createQualityNcr({...ncrForm});showNcr.value=false;showToast('质量异常已创建');await loadNcr();await loadDashboard()}catch(e){showToast(e.message||'创建异常失败','error')}}
async function openNcrDetail(row){try{const result=await api.domains.qualityManagement.qualityNcrDetail(row.id);ncrDetail.value=result.ncr;showNcrDetail.value=true}catch(e){showToast(e.message||'异常详情加载失败','error')}}

function emptyStandardItem(){return {item_code:'',item_name:'',item_type:'numeric',unit:'',nominal_value:'',lower_limit:'',upper_limit:'',required:true,weight:0,inspection_method:'',acceptance_criteria:''}}
function openStandard(){Object.assign(standardForm,{id:null,standard_no:'',name:'',product_code:'',route_id:null,process_id:null,inspection_type:'in_process',version:1,status:'active',gate_mode:'soft',sampling_mode:'fixed',sample_value:1,min_score:85,acceptance_rule:'all_required_pass',notes:'',items:[emptyStandardItem()]});showStandard.value=true}
async function editStandard(row){const d=await api.domains.qualityManagement.qualityStandard(row.id);Object.assign(standardForm,{...d.standard,items:(d.standard.items||[]).map(i=>({...i,required:!!i.required}))});showStandard.value=true}
function addStandardItem(){standardForm.items.push(emptyStandardItem())}
async function saveStandard(){try{const payload=JSON.parse(JSON.stringify(standardForm));if(standardForm.id)await api.domains.qualityManagement.updateQualityStandard(standardForm.id,payload);else await api.domains.qualityManagement.createQualityStandard(payload);showStandard.value=false;showToast('质量标准已保存');await loadStandards()}catch(e){showToast(e.message||'保存失败','error')}}
async function archiveStandard(row){if(!confirm(`确定停用质量标准 ${row.standard_no} 吗？`))return;await api.domains.qualityManagement.archiveQualityStandard(row.id);await loadStandards()}

function openPlan(){Object.assign(planForm,{id:null,name:'',standard_id:null,product_code:'',route_id:null,process_id:null,trigger_type:'manual',inspection_type:'in_process',gate_mode:'soft',sampling_mode:'fixed',sample_value:1,frequency_qty:0,due_minutes:120,status:'active'});showPlan.value=true}
function editPlan(row){Object.assign(planForm,{...row,route_id:row.route_id||null,process_id:row.process_id||null,standard_id:row.standard_id||null});showPlan.value=true}
async function savePlan(){try{const payload={...planForm};if(planForm.id)await api.domains.qualityManagement.updateQualityPlan(planForm.id,payload);else await api.domains.qualityManagement.createQualityPlan(payload);showPlan.value=false;showToast('检验方案已保存');await loadPlans()}catch(e){showToast(e.message||'保存失败','error')}}
async function archivePlan(row){if(!confirm(`确定停用检验方案 ${row.name} 吗？`))return;await api.domains.qualityManagement.archiveQualityPlan(row.id);await loadPlans()}

function openTask(){Object.assign(taskForm,{order_id:null,process_id:null,inspection_type:'manual',standard_id:null,serial_no:'',batch_no:'',sample_qty:1,gate_mode:'soft',priority:'normal',assigned_to:null});showTask.value=true}
async function saveTask(){try{await api.domains.qualityManagement.createQualityTask({...taskForm});showTask.value=false;showToast('检验任务已创建');await loadTasks()}catch(e){showToast(e.message||'创建失败','error')}}
async function startTask(row){try{await api.domains.qualityManagement.startQualityTask(row.id);await openInspection(row)}catch(e){showToast(e.message||'开始任务失败','error')}}
async function openInspection(row){try{const d=await api.domains.qualityManagement.qualityTask(row.id);inspectionTask.value=d.task;const measurements=(d.task.standard_items||[]).map(item=>({item_id:item.id,item_code:item.item_code,item_name:item.item_name,item_type:item.item_type,unit:item.unit,weight:item.weight,value:item.item_type==='boolean'?true:item.item_type==='score'?item.weight:'',note:'',nominal:item.nominal_value,lower:item.lower_limit,upper:item.upper_limit,criteria:item.acceptance_criteria}));Object.assign(inspectionForm,{quantity_checked:d.task.sample_qty||1,quantity_failed:0,result:'pass',defect_level:'',defect_category:'',responsible_process_id:d.task.process_id||null,notes:'',measurements});showInspection.value=true}catch(e){showToast(e.message||'任务详情加载失败','error')}}
async function submitInspection(){try{await api.domains.qualityManagement.inspectQualityTask(inspectionTask.value.id,JSON.parse(JSON.stringify(inspectionForm)));showInspection.value=false;showToast('检验结果已提交');await loadTasks();await loadDashboard()}catch(e){showToast(e.message||'提交失败','error')}}

function openDisposition(row){dispositionRow.value=row;Object.assign(dispositionForm,{disposition:row.disposition&&row.disposition!=='pending'?row.disposition:'rework',owner_id:row.owner_id||null,responsible_user_id:row.responsible_user_id||null,responsible_process_id:row.responsible_process_id||row.process_id||null,due_at:row.due_at?.slice(0,10)||'',root_cause:row.root_cause||'',corrective_action:row.corrective_action||'',note:''});showDisposition.value=true}
async function saveDisposition(){try{await api.domains.qualityManagement.disposeQualityNcr(dispositionRow.value.id,{...dispositionForm});showDisposition.value=false;showToast('不合格处置已保存');await loadNcr();await loadDashboard()}catch(e){showToast(e.message||'处置失败','error')}}

function openCapa(row=null,ncr=null){Object.assign(capaForm,row?{...row}:{id:null,ncr_id:ncr?.id||null,title:ncr?`${ncr.ncr_no} 质量改进`:'',problem_description:ncr?.description||'',root_cause:'',corrective_action:'',preventive_action:'',owner_id:null,due_at:'',status:'open',effectiveness_result:''});showCapa.value=true}
async function saveCapa(){try{const payload={...capaForm};if(capaForm.id)await api.domains.qualityManagement.updateQualityCapa(capaForm.id,payload);else await api.domains.qualityManagement.createQualityCapa(payload);showCapa.value=false;showToast('CAPA 已保存');if(activeTab.value==='capa')await loadCapa()}catch(e){showToast(e.message||'保存失败','error')}}

function openSupplier(){Object.assign(supplierForm,{supplier_id:null,material_id:null,batch_no:'',delivery_no:'',quantity_checked:1,quantity_failed:0,result:'pass',score_total:100,defect_level:'',defect_category:'',notes:''});showSupplier.value=true}
async function saveSupplierInspection(){try{await api.domains.qualityManagement.createSupplierInspection({...supplierForm});showSupplier.value=false;showToast('来料检验已保存');await loadSuppliers();await loadDashboard()}catch(e){showToast(e.message||'保存失败','error')}}

function openGauge(row=null){Object.assign(gaugeForm,row?{...row}:{id:null,gauge_no:'',name:'',model:'',measurement_range:'',accuracy:'',location:'',calibration_cycle_days:365,status:'active',owner_id:null,remark:''});showGauge.value=true}
async function saveGauge(){try{const payload={...gaugeForm};if(gaugeForm.id)await api.domains.qualityManagement.updateQualityGauge(gaugeForm.id,payload);else await api.domains.qualityManagement.createQualityGauge(payload);showGauge.value=false;showToast('量具已保存');await loadGauges()}catch(e){showToast(e.message||'保存失败','error')}}
function openCalibration(row){calibrationGauge.value=row;const today=new Date();const next=new Date(today.getTime()+(row.calibration_cycle_days||365)*86400000);Object.assign(calibrationForm,{calibrated_at:today.toISOString().slice(0,10),next_calibration_at:next.toISOString().slice(0,10),result:'pass',certificate_no:'',organization:'',notes:''});showCalibration.value=true}
async function saveCalibration(){try{await api.domains.qualityManagement.calibrateQualityGauge(calibrationGauge.value.id,{...calibrationForm});showCalibration.value=false;showToast('校准记录已保存');await loadGauges();await loadDashboard()}catch(e){showToast(e.message||'保存失败','error')}}
async function saveRules(){try{Object.assign(ruleForm,await api.domains.qualityManagement.saveQualityRules({...ruleForm}));showToast('质量门禁规则已保存')}catch(e){showToast(e.message||'保存失败','error')}}

function typeLabel(v){return Object.fromEntries(inspectionTypeOptions.map(i=>[i.value,i.label]))[v]||v||'-'}
function triggerLabel(v){return Object.fromEntries(triggerOptions.map(i=>[i.value,i.label]))[v]||v||'-'}
function taskStatusLabel(v){return {pending:'待检',in_progress:'检验中',passed:'已通过',failed:'不合格',cancelled:'已取消'}[v]||v}
function ncrStatusLabel(v){return {open:'待处置',processing:'处理中',pending_reinspection:'待复检',closed:'已关闭',cancelled:'已取消'}[v]||v}
function capaStatusLabel(v){return {open:'待分析',processing:'执行中',verified:'已验证',closed:'已关闭'}[v]||v}
function resultLabel(v){return {pass:'合格',rework:'返修',scrap:'报废',return:'退货'}[v]||v||'-'}
function resultClass(v){return v==='pass'?'badge-success':v==='rework'?'badge-warning':'badge-danger'}
function statusClass(v){return ['passed','closed','verified'].includes(v)?'badge-success':['pending','open','pending_reinspection'].includes(v)?'badge-warning':['failed','cancelled'].includes(v)?'badge-danger':'badge-info'}
function defectLevelLabel(v){return {minor:'轻微',general:'一般',severe:'严重',critical:'致命'}[v]||'-'}
function dispositionLabel(v){return {pending:'待判定',rework:'返修',scrap:'报废',concession:'让步接收',isolate:'隔离',return:'退回'}[v]||v||'-'}
function gateLabel(v){return {hard:'强拦截',soft:'软提示',off:'关闭'}[v]||v||'-'}
function gaugeStatusLabel(v){return {active:'在用',suspended:'停用',scrapped:'报废'}[v]||v}
function sourceLabel(v){return {inspection:'生产检验',supplier_inspection:'来料检验',legacy:'历史抽检'}[v]||v||'-'}
function scopeLabel(row){return [row.product_code,row.route_name,row.process_name].filter(Boolean).join(' / ')||'全局'}
function samplingLabel(row){return row.sampling_mode==='full'?'全检':row.sampling_mode==='ratio'?`${row.sample_value}%`:`${row.sample_value} 件`}
function passRate(checked,failed){return checked?Math.round((checked-failed)*1000/checked)/10:0}
function supplierPassRate(row){return row.inspection_count?Math.round(row.pass_count*1000/row.inspection_count)/10:0}
function measurementStandard(m){if(m.item_type==='numeric')return [m.lower!==''?`≥${m.lower}`:'',m.upper!==''?`≤${m.upper}`:'',m.unit].filter(Boolean).join(' ');if(m.item_type==='score')return `满分 ${m.weight}`;return m.criteria||m.nominal||'按标准判定'}

onMounted(async()=>{if(!visibleTabs.value.some(tab=>tab.key===activeTab.value))activeTab.value='overview';await loadRefs();await loadStandards();await loadActive()})
</script>

<style scoped>
.qm-page{padding:var(--space-6)}.qm-shell{min-height:620px}.qm-header{display:flex;align-items:center;gap:var(--space-3);flex-wrap:wrap}.qm-header h3{margin:0}.qm-tabs,.qm-segments{display:flex;gap:var(--space-1);flex-wrap:wrap}.qm-actions{margin-left:auto;display:flex;align-items:center;gap:var(--space-2);flex-wrap:wrap}.qm-search{width:180px}.qm-filter{width:130px}.qm-body{padding-top:var(--space-3)}.qm-wide{min-width:1180px}.qm-row-actions{white-space:nowrap}.qm-row-actions .btn+.btn{margin-left:5px}.cell-muted{font-size:var(--text-xs-alt);color:var(--text-placeholder);margin-top:3px}.qm-overdue-row{background:var(--danger-light)}.qm-section-head{display:flex;align-items:center;justify-content:space-between;gap:var(--space-3);margin:0 0 var(--space-3)}.qm-section-head h4{margin:0}.qm-second{margin-top:var(--space-6)}.qm-segments{margin-bottom:var(--space-4)}.qm-summary-table{margin-bottom:var(--space-5);max-width:900px}.qm-analytics-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-6);margin-top:var(--space-6)}.qm-date-filter{display:flex;align-items:center;gap:var(--space-2);margin-bottom:var(--space-5)}.qm-date-filter .form-input{width:160px}.qm-rules{max-width:900px}.qm-rule-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-3) var(--space-6);margin-bottom:var(--space-5)}.qm-rule-grid label{display:grid;grid-template-columns:1fr 160px;align-items:center;gap:var(--space-3);padding:10px 0;border-bottom:1px solid var(--border)}.qm-rule-grid input[type=checkbox]{justify-self:end;width:18px;height:18px}.qm-modal{width:min(760px,94vw);max-height:88vh;display:flex;flex-direction:column}.qm-modal-wide{width:min(1120px,96vw)}.qm-modal .modal-body{overflow:auto}.qm-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-3)}.qm-form-grid label,.qm-full-label{display:flex;flex-direction:column;gap:6px;font-size:var(--text-sm);color:var(--text-secondary)}.qm-full-label{margin-top:var(--space-3)}.qm-item-table{min-width:980px}.qm-item-table .form-input{min-width:80px}.qm-inspection-meta{display:flex;gap:var(--space-4);flex-wrap:wrap;padding:10px 12px;margin-bottom:var(--space-3);background:var(--bg-hover);font-weight:600}.qm-inspection-form{margin-top:var(--space-4)}.qm-review-queue{padding:var(--space-4);margin-bottom:var(--space-5)}.qm-review-item,.qm-ncr-detail-link{display:flex;align-items:center;justify-content:space-between;gap:var(--space-3);padding:10px 0;border-bottom:1px solid var(--border-light)}.qm-review-item:last-child,.qm-ncr-detail-link:last-child{border-bottom:0}.qm-review-item>div,.qm-ncr-detail-link>span{flex:1;min-width:0}.qm-ncr-detail-list{margin-bottom:var(--space-5)}.qm-timeline{display:flex;flex-direction:column;gap:var(--space-3)}.qm-timeline-item{padding:10px 12px;border-left:3px solid var(--primary);background:var(--bg-hover)}.qm-timeline-item span{display:block;color:var(--text-placeholder);font-size:var(--text-xs);margin:3px 0}.qm-timeline-item div{color:var(--text-secondary)}
@media(max-width:1000px){.qm-page{padding:var(--space-3)}.qm-actions{margin-left:0;width:100%}.qm-analytics-grid,.qm-rule-grid{grid-template-columns:1fr}.qm-form-grid{grid-template-columns:1fr}.qm-rule-grid label{grid-template-columns:1fr 150px}.qm-search{width:min(100%,220px)}}
</style>
